{
  pkgs,
  lib,
  config,
  ...
}:
let
  inherit (lib) mkDefault;
in
{
  config = lib.mkIf config.teq.nixos.enable {
    services.envfs = {
      enable = mkDefault true;
      extraFallbackPathCommands = mkDefault ''
        ln -s ${lib.getExe pkgs.bash} $out/bash
        ln -s ${lib.getExe pkgs.zsh} $out/zsh
        ln -s ${lib.getExe pkgs.fish} $out/fish
        ln -s ${lib.getExe pkgs.xonsh} $out/xonsh
      '';
    };
    programs.nix-ld.enable = mkDefault true;

    programs.nix-ld.libraries =
      with pkgs;
      [
        acl
        attr
        bzip2
        curl
        dbus
        expat
        fontconfig
        freetype
        fuse
        fuse3
        icu
        libnotify
        libsodium
        libssh
        libunwind
        libusb1
        libuuid
        nspr
        nss
        stdenv.cc.cc
        openssl
        glib-networking
        util-linux
        zlib
        zstd
        libz
      ]
      ++ lib.optionals config.hardware.graphics.enable [
        pipewire
        cups
        libxkbcommon
        pango
        mesa
        mesa.llvmPackages.llvm.lib
        vulkan-loader
        wayland
        egl-wayland
        wayland-utils
        libxcb
        libxdamage
        libxshmfence
        libxxf86vm
        libelf
        (lib.getLib elfutils)
        libdrm
        libglvnd
        libpulseaudio
        atk
        cairo
        gdk-pixbuf
        alsa-lib
        at-spi2-atk
        at-spi2-core
        glib
        gtk2
        gtk3
        libGL
        libappindicator-gtk3
        libx11
        libxscrnsaver
        libxcomposite
        libxcursor
        libxdamage
        libxext
        libxfixes
        libxi
        libxrandr
        libxrender
        libxtst
        libxcb
        libxkbfile
        libxshmfence
        libxinerama
        libsm
        libice
        libxt
        libxmu
        lsb-release
        pciutils
        glibc_multi.bin
        xrandr
        which
        perl
        xdg-utils
        iana-etc
        python3
        xdg-user-dirs
        sqlite
        libdecor
        libva
        libva-utils
        ocamlPackages.alsa
        harfbuzz
        libthai
        brotli
        libxml2
        pulseaudio
        systemd
        x264
        libplist
        lsof
        file
        curlWithGnuTls
        libcap
        SDL2
        dbus-glib
        gsettings-desktop-schemas
        ffmpeg
        libudev0-shim
        libogg
        libvorbis
        SDL
        SDL2_image
        glew_1_10
        libidn
        tbb
        flac
        freeglut
        libjpeg
        libpng
        libpng12
        libsamplerate
        libmikmod
        libtheora
        libtiff
        pixman
        speex
        SDL_image
        SDL_mixer
        SDL2_ttf
        SDL2_mixer
        libdbusmenu-gtk3
        libindicator-gtk3
        libcaca
        libcanberra
        libgcrypt
        libvpx
        librsvg
        libxft
        libvdpau
        libGLU
        libbsd
        libidn2
        libpsl
        nghttp2.lib
        rtmpdump
        procps
        usbutils
        udev
        gst_all_1.gstreamer
        gst_all_1.gst-plugins-ugly
        gst_all_1.gst-plugins-base
        json-glib
        libxcrypt
        mono
        xkeyboard-config
        libpciaccess
      ];
  };
}
